name: tests
on: [pull_request, push]
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.8"
      - run: pip install pytest
      - run: python -m pytest -q jevaluate/scripts jevaluate-eval jevaluate-harness
